# Generated by Django 3.2 on 2021-04-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmplpyeeStatistics',
            new_name='EmployeeStatistics',
        ),
    ]
