# Generated by Django 3.2 on 2021-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210426_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationinformation',
            old_name='emplpyee_statistics',
            new_name='employee_statistics',
        ),
    ]
