# Generated by Django 3.2 on 2021-04-29 14:22

from django.db import migrations, models
import single_instance_model.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rename_emplpyee_statistics_organizationinformation_employee_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionLable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
            ],
            bases=(models.Model, single_instance_model.models.SingleInstanceModel),
        ),
        migrations.CreateModel(
            name='StatisticsLable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
            ],
            bases=(models.Model, single_instance_model.models.SingleInstanceModel),
        ),
    ]
